name: sync dependencies
on:
  push:
    branches: 
      - master
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: branch-sync
  cancel-in-progress: false

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: nerjs/branch-sync@v1
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          base: master
          head: dependencies